# Generated by Django 2.2.10 on 2021-03-23 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210323_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='problem',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
