# Generated by Django 2.2.10 on 2021-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20210323_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
