# Generated by Django 2.2.10 on 2021-07-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20210325_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='user_count',
        ),
        migrations.AlterField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmts_p', to='problems.Problem'),
        ),
    ]
