# Generated by Django 2.2.10 on 2021-07-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20210714_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='rating',
            new_name='vote',
        ),
    ]
