# Generated by Django 2.2.10 on 2021-07-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20210716_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
