# Generated by Django 2.2.10 on 2021-07-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_auto_20210716_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='body',
            new_name='s_body',
        ),
    ]
