# Generated by Django 2.2.10 on 2021-07-16 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0011_auto_20210716_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='solution',
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.Solution')),
            ],
        ),
    ]
