# Generated by Django 2.2.10 on 2021-07-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20210716_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='best_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Solution'),
        ),
    ]
