# Generated by Django 2.2.10 on 2021-03-14 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.FileField(upload_to='uploads/')),
                ('batch', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=60)),
                ('facebook', models.URLField(blank=True, max_length=60)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
