# Generated by Django 2.2.10 on 2021-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210714_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
